### ISSUE TITLE
http: panic serving 127.0.0.1:56544: unknown state root

### ISSUE THREAD

**Issue by dschuessler** [alecthomas/chroma#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I recently started trying to implement a lexer. I cannot rule out that I am at fault, but I assume that this is not expected behavior.

### To Reproduce

1. Create `lexers/embedded/webvtt.xml`.
2. Copy and paste this code inside:

```XML
<lexer>
    <config>
        <name>WebVTT</name>
        <alias>vtt</alias>
        <filename>*.vtt</filename>
        <mime_type>text/vtt</mime_type>
    </config>
    <rules>
        <state name="root">
            <rule pattern="\AWEBVTT">
                <token type="Keyword" />
            </rule>
            <rule pattern="\d{2}:\d{2}\.\d{3}">
                <token type="Name" />
            </rule>
        </state>
    </rules>
</lexer>
```

3. Navigate to `cmd/chromad`.
4. Run `go run . --csrf-key=securekey`.
5. Navigate to http://127.0.0.1:8080/
6. Select "WebVTT" in the code dropdown.
7. Change `<token type="Name" />` to `<token type="Number" />`.

Expected behavior: The server doesn't panic.

Actual behavior: The server panics.

```
2024/12/12 16:14:10 http: panic serving 127.0.0.1:56591: unknown state root
goroutine 28 [running]:
net/http.(*conn).serve.func1()
        /opt/homebrew/Cellar/go/1.23.4/libexec/src/net/http/server.go:1947 +0xb0
panic({0x100f9b5a0?, 0x140002a2250?})
        /opt/homebrew/Cellar/go/1.23.4/libexec/src/runtime/panic.go:785 +0x124
github.com/alecthomas/chroma/v2.(*LexerState).Iterator(0x140000e6480)
        /Users/x/Developer/Repositories/chroma/regexp.go:213 +0x68c
github.com/alecthomas/chroma/v2.(*coalescer).Tokenise.func1()
        /Users/x/Developer/Repositories/chroma/coalesce.go:15 +0x34
github.com/alecthomas/chroma/v2.Iterator.Tokens(0x140003d8060)
        /Users/x/Developer/Repositories/chroma/iterator.go:15 +0x2c
github.com/alecthomas/chroma/v2/formatters/html.(*Formatter).Format(0x1400033a5a0, {0x10103ce58, 0x140003e0000}, 0x1400009be00, 0x140002d7678?)
        /Users/x/Developer/Repositories/chroma/formatters/html/html.go:220 +0x30
main.render(0x14000276140)
        /Users/x/Developer/Repositories/chroma/cmd/chromad/main.go:134 +0x230
main.renderHandler({0x101040f78, 0x140005ea0e0}, 0x140000b7040)
        /Users/x/Developer/Repositories/chroma/cmd/chromad/main.go:97 +0x14c
net/http.HandlerFunc.ServeHTTP(0x140000b6f00?, {0x101040f78?, 0x140005ea0e0?}, 0x58?)
        /opt/homebrew/Cellar/go/1.23.4/libexec/src/net/http/server.go:2220 +0x38
github.com/gorilla/mux.(*Router).ServeHTTP(0x140000e6600, {0x101040f78, 0x140005ea0e0}, 0x140000b6c80)
        /Users/x/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x194
github.com/gorilla/csrf.(*csrf).ServeHTTP(0x140000e66c0, {0x101040f78, 0x140005ea0e0}, 0x140000b6000)
        /Users/x/go/pkg/mod/github.com/gorilla/csrf@v1.7.2/csrf.go:306 +0x514
github.com/gorilla/handlers.(*cors).ServeHTTP(0x1400033a900, {0x101040f78, 0x140005ea0e0}, 0x140000b6000)
        /Users/x/go/pkg/mod/github.com/gorilla/handlers@v1.5.2/cors.go:136 +0x5bc
net/http.serverHandler.ServeHTTP({0x10103f210?}, {0x101040f78?, 0x140005ea0e0?}, 0x6?)
        /opt/homebrew/Cellar/go/1.23.4/libexec/src/net/http/server.go:3210 +0xbc
net/http.(*conn).serve(0x140002181b0, {0x101041760, 0x140001c3410})
        /opt/homebrew/Cellar/go/1.23.4/libexec/src/net/http/server.go:2092 +0x4fc
created by net/http.(*Server).Serve in goroutine 1
        /opt/homebrew/Cellar/go/1.23.4/libexec/src/net/http/server.go:3360 +0x3dc
```

**Comment by alecthomas** [comment]
This is not unexpected. A better way to develop lexers is to move the xml into the root and do this:

```
~/dev/chroma $ echo WEBVTT | ./bin/chroma --lexer webvtt.xml
chroma: error: WebVTT: failed to compile rules: webvtt.xml: Number does not belong to TokenType values
```

Lexers in `lexers/embedded` are expected to be functional. They're compiled on demand and panic if they're not valid.

**Comment by alecthomas** [comment]
What I've wanted to do for a while is extend `chromad` so that it has an editor for new lexers/styles, but I haven't had the time.
