### ISSUE TITLE
Slice bounds out of range in go-html-template

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#126]
```bash
goroutine 395 [running]:
github.com/gohugoio/hugo/vendor/github.com/alecthomas/chroma.splitToken(...)
	/Users/bep/go/src/github.com/gohugoio/hugo/vendor/github.com/alecthomas/chroma/delegate.go:132
github.com/gohugoio/hugo/vendor/github.com/alecthomas/chroma.(*delegatingLexer).Tokenise(0xc420343360, 0x0, 0xc424082600, 0x5fd, 0x1, 0xc4203eae18, 0x195b400)
	/Users/bep/go/src/github.com/gohugoio/hugo/vendor/github.com/alecthomas/chroma/delegate.go:102 +0x105e
github.com/gohugoio/hugo/vendor/github.com/alecthomas/chroma.(*coalescer).Tokenise(0xc4254e53d0, 0x0, 0xc424082600, 0x5fd, 0xc4203eae90, 0xc424ec5301, 0x102a939)
```

Input:

```html
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>{{ if eq  .Title  .Site.Title }}{{ .Site.Title }}{{ else }}{{ with .Title }}{{.}} on {{ end }}{{ .Site.Title }}{{ end }}</title>
    <link>{{ .Permalink }}</link>
    <description>Recent content {{ if ne  .Title  .Site.Title }}{{ with .Title }}in {{.}} {{ end }}{{ end }}on {{ .Site.Title }}</description>
    <generator>Hugo -- gohugo.io</generator>{{ with .Site.LanguageCode }}
    <language>{{.}}</language>{{end}}{{ with .Site.Author.email }}
    <managingEditor>{{.}}{{ with $.Site.Author.name }} ({{.}}){{end}}</managingEditor>{{end}}{{ with .Site.Author.email }}
    <webMaster>{{.}}{{ with $.Site.Author.name }} ({{.}}){{end}}</webMaster>{{end}}{{ with .Site.Copyright }}
    <copyright>{{.}}</copyright>{{end}}{{ if not .Date.IsZero }}
    <lastBuildDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" | safeHTML }}</lastBuildDate>{{ end }}
    {{ with .OutputFormats.Get "RSS" }}
        {{ printf "<atom:link href=%q rel=\"self\" type=%q />" .Permalink .MediaType | safeHTML }}
    {{ end }}
    {{ range .Data.Pages }}
    <item>
      <title>{{ .Title }}</title>
      <link>{{ .Permalink }}</link>
      <pubDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" | safeHTML }}</pubDate>
      {{ with .Site.Author.email }}<author>{{.}}{{ with $.Site.Author.name }} ({{.}}){{end}}</author>{{end}}
      <guid>{{ .Permalink }}</guid>
      <description>{{ .Summary | html }}</description>
    </item>
    {{ end }}
  </channel>
</rss>
```

**Comment by kaushalmodi** [comment]
I confirm the same error from this input too:

```html
{{ $headless := .Site.GetPage "page" "some-headless-bundle" }}
{{ $reusablePages := $headless.Resources.Match "author*" }}
<h2>Authors</h2>
{{ range $reusablePages }}
    <h3>{{ .Title }}</h3>
    {{ .Content }}
{{ end }}
```

---

Backtrace:

```text
panic: runtime error: slice bounds out of range

goroutine 313 [running]:
github.com/alecthomas/chroma.splitToken(...)
        /home/kmodi/go.apps/src/github.com/alecthomas/chroma/delegate.go:132
github.com/alecthomas/chroma.(*delegatingLexer).Tokenise(0xc420321340, 0x0, 0xc4200289a0, 0xdd, 0x0, 0x10, 0xd54780)
        /home/kmodi/go.apps/src/github.com/alecthomas/chroma/delegate.go:102 +0x105e
github.com/alecthomas/chroma.(*coalescer).Tokenise(0xc420409940, 0x0, 0xc4200289a0, 0xdd, 0xc4202ac9f8, 0xc42200d301, 0x429039)
        /home/kmodi/go.apps/src/github.com/alecthomas/chroma/coalesce.go:10 +0x6f
github.com/gohugoio/hugo/helpers.chromaHighlight(0xfc4a80, 0xc4239e4310, 0xc4200289a0, 0xdd, 0xc4230eb1a0, 0x10, 0xe10bef, 0x7, 0xfc4dc0, 0xc421ee6f00, ...)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/helpers/pygments.go:199 +0x15b
github.com/gohugoio/hugo/helpers.highlighters.chromaHighlight(0xc4202b6f60, 0x4efa00, 0xc4203a7760, 0x10, 0xc4200289a0, 0xdd, 0xc4230eb1a0, 0x10, 0x0, 0x0, ...)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/helpers/pygments.go:83 +0x1f4
github.com/gohugoio/hugo/helpers.(highlighters).(github.com/gohugoio/hugo/helpers.chromaHighlight)-fm(0xc4200289a0, 0xdd, 0xc4230eb1a0, 0x10, 0x0, 0x0, 0xc4230eb120, 0x3, 0xc4201e6a94, 0x3)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/helpers/content.go:98 +0x9c
github.com/gohugoio/hugo/helpers.(*HugoHTMLRenderer).BlockCode(0xc423b68460, 0xc4239e47e0, 0xc4201e69c0, 0xde, 0x192, 0xc4230eb1a0, 0x10)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/helpers/content_renderer.go:39 +0x169
github.com/gohugoio/hugo/vendor/github.com/russross/blackfriday.(*parser).fencedCodeBlock(0xc42481c000, 0xc4239e47e0, 0xc4236bda8b, 0x221b, 0x234d, 0x1, 0x0)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/vendor/github.com/russross/blackfriday/block.go:700 +0x30f
github.com/gohugoio/hugo/vendor/github.com/russross/blackfriday.(*parser).block(0xc42481c000, 0xc4239e47e0, 0xc4236bc800, 0x34a6, 0x35d8)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/vendor/github.com/russross/blackfriday/block.go:104 +0x666
github.com/gohugoio/hugo/vendor/github.com/russross/blackfriday.secondPass(0xc42481c000, 0xc4236bc800, 0x34a6, 0x35d8, 0xc4236bc800, 0x34a6, 0x35d8)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/vendor/github.com/russross/blackfriday/markdown.go:459 +0x87
github.com/gohugoio/hugo/vendor/github.com/russross/blackfriday.MarkdownOptions(0xc4236b9000, 0x366c, 0x3800, 0xff6580, 0xc423b68460, 0xea5f, 0x0, 0x0, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/vendor/github.com/russross/blackfriday/markdown.go:389 +0x230
github.com/gohugoio/hugo/vendor/github.com/russross/blackfriday.Markdown(0xc4236b9000, 0x366c, 0x3800, 0xff6580, 0xc423b68460, 0xea5f, 0x4103b9, 0xc4239e4380, 0x70)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/vendor/github.com/russross/blackfriday/markdown.go:343 +0x70
github.com/gohugoio/hugo/helpers.ContentSpec.markdownRender(0xc420252fc0, 0x0, 0x0, 0x0, 0x0, 0x46, 0x10001, 0xc4201e4210, 0xc4200b7f50, 0xfd86e0, ...)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/helpers/content.go:332 +0xfc
github.com/gohugoio/hugo/helpers.ContentSpec.RenderBytes(0xc420252fc0, 0x0, 0x0, 0x0, 0x0, 0x46, 0x10001, 0xc4201e4210, 0xc4200b7f50, 0xfd86e0, ...)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/helpers/content.go:456 +0x2e1
github.com/gohugoio/hugo/hugolib.(*Page).renderContent(0xc421f75400, 0xc4236b9000, 0x366c, 0x3800, 0xc4236b9000, 0x366c, 0x3800)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/hugolib/page.go:732 +0x243
github.com/gohugoio/hugo/hugolib.(*contentHandlers).handlePageContent.func1(0xc421ee6000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/hugolib/page_bundler_handlers.go:289 +0x29c
github.com/gohugoio/hugo/hugolib.(*contentHandlers).processFirstMatch.func1(0xc421ee6000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/hugolib/page_bundler_handlers.go:84 +0xa0
github.com/gohugoio/hugo/hugolib.(*contentHandlers).parsePage.func1(0xc421ee6000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/hugolib/page_bundler_handlers.go:265 +0x385
github.com/gohugoio/hugo/hugolib.(*contentHandlers).processFirstMatch.func1(0xc421ee6000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/hugolib/page_bundler_handlers.go:84 +0xa0
github.com/gohugoio/hugo/hugolib.(*siteContentProcessor).readAndConvertContentBundle(0xc421ef7860, 0xc423524040, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/hugolib/page_bundler.go:187 +0x91
github.com/gohugoio/hugo/hugolib.(*siteContentProcessor).process.func4(0x8, 0xeb3080)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/hugolib/page_bundler.go:153 +0x139
github.com/gohugoio/hugo/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc421e32780, 0xc423988900)
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/gohugoio/hugo/vendor/golang.org/x/sync/errgroup.(*Group).Go
        /home/kmodi/go.apps/src/github.com/gohugoio/hugo/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

**Comment by kaushalmodi** [comment]
Thanks for the fix! I confirm the fix.
