### ISSUE TITLE
Error with chroma after brew upgrade hugo command

### ISSUE THREAD

**Issue by ValentinChevoleau** [alecthomas/chroma#342]
hi 

> with hugo version = 0.66

**After upgrade hugo i have this error when i use hugo commande with MAC OS Sierra**
**commande** : hugo server

```
SIGILL: illegal instruction
PC=0x406a670 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc00016b4d8 sp=0xc00016b4d0 pc=0x406a670
strings.(*Builder).WriteString(...)
/usr/local/Cellar/go/1.14/libexec/src/strings/builder.go:123
strings.Join(0xc00055e000, 0xf4, 0xf4, 0x58365c8, 0x1, 0xc00016b608, 0x400f688)
/usr/local/Cellar/go/1.14/libexec/src/strings/strings.go:442 +0x2d6 fp=0xc00016b5b0 sp=0xc00016b4d8 pc=0x40fde16
github.com/alecthomas/chroma.Words(0x0, 0x0, 0x5836873, 0x2, 0xc00055e000, 0xf4, 0xf4, 0xc000041000, 0x84)
/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/alecthomas/chroma@v0.7.1/regexp.go:144 +0xe5 fp=0xc00016b638 sp=0xc00016b5b0 pc=0x4564aa5
github.com/alecthomas/chroma/lexers/s.init()
/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/alecthomas/chroma@v0.7.1/lexers/s/systemverilog.go:43 +0x1a774 fp=0xc00016bda8 sp=0xc00016b638 pc=0x46a9694
runtime.doInit(0x692b360)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc00016bdd8 sp=0xc00016bda8 pc=0x40456aa
runtime.doInit(0x6938540)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016be08 sp=0xc00016bdd8 pc=0x4045677
runtime.doInit(0x6931f40)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016be38 sp=0xc00016be08 pc=0x4045677
runtime.doInit(0x69300e0)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016be68 sp=0xc00016be38 pc=0x4045677
runtime.doInit(0x6930080)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016be98 sp=0xc00016be68 pc=0x4045677
runtime.doInit(0x693c940)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016bec8 sp=0xc00016be98 pc=0x4045677
runtime.doInit(0x6932ec0)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016bef8 sp=0xc00016bec8 pc=0x4045677
runtime.doInit(0x6941280)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016bf28 sp=0xc00016bef8 pc=0x4045677
runtime.doInit(0x69408e0)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016bf58 sp=0xc00016bf28 pc=0x4045677
runtime.doInit(0x69285a0)
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00016bf88 sp=0xc00016bf58 pc=0x4045677
runtime.main()
/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc00016bfe0 sp=0xc00016bf88 pc=0x4038aae
runtime.goexit()
/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00016bfe8 sp=0xc00016bfe0 pc=0x4068df1

rax 0x2e3
rbx 0x2ea
rcx 0xc00016b580
rdx 0x7
rdi 0xc0005602e2
rsi 0xc000560000
rbp 0xc00016b5a0
rsp 0xc00016b4d0
r8 0x58472a0
r9 0x2e2
r10 0xc00016b580
r11 0x2e3
r12 0xc000560000
r13 0x757
r14 0x5c18420
r15 0x0
rip 0x406a670
rflags 0x10246
cs 0x2b
fs 0x0
gs 0x0
```

**Comment by alecthomas** [comment]
This is the most useless bug report I've ever seen.

How am I supposed to reproduce this? What version of Chroma is it? What input is it consuming that caused this? How do I reproduce it with Chroma? There are *INSTRUCTIONS* in the bug filing template.

Feel free to reopen this issue, or file another one, when you can provide more information.

**Comment by alecthomas** [comment]
BTW, FWIW there's almost zero chance this is a bug in Chroma. SIGILL usually indicates a hardware issue, or a bug in the Go runtime or compiler.

**Comment by alecthomas** [comment]
Apologies for being a bit harsh in my initial response, I could have made my point (which still stands) without being quite so direct.

**Comment by ValentinChevoleau** [comment]
hello,
Don’t apologize, I wasn’t sure how to ask for help, you were right about my lack of information.
In fact I have updated HUGO from 0.65 to 0.66 on my macbook of late 2009 ave hight sierra.
Following the update with brew upgrade HUGO, I get the error quoted a little above.
I don't hunderstand how i can fixe this problem because i 'm new go user.
it's hugo's dev who think chroma is probleme
