### ISSUE TITLE
Panic when running on macOS Monterrey 12.2 using the darwin-amd64 binary

### ISSUE THREAD

**Issue by DavidGamba** [alecthomas/chroma#611]
```
$ wget https://github.com/alecthomas/chroma/releases/download/v2.0.0-alpha2/chroma-2.0.0-alpha2-darwin-amd64.tar.gz
$ tar -xvzf chroma-2.0.0-alpha2-darwin-amd64.tar.gz
$ ./chroma 
panic: open embedded/common_lisp.xml: file does not exist

goroutine 1 [running]:
github.com/alecthomas/chroma/v2.MustNewXMLLexer(...)
        /home/runner/work/chroma/chroma/serialise.go:121
github.com/alecthomas/chroma/v2/lexers.init()
        /home/runner/work/chroma/chroma/lexers/cl.go:232 +0x4ec5
```

Can't install using `go install` either:

```
$ go install github.com/alecthomas/chroma/cmd/chroma@latest
go install: github.com/alecthomas/chroma/cmd/chroma@latest (in github.com/alecthomas/chroma/cmd/chroma@v0.0.0-20220221052627-ac30dbedfc58):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by alecthomas** [comment]
The latter problem is because you must install it from within `cmd/chroma` as the command-line is its own module: `cd cmd/chroma && go install .`

**Comment by DavidGamba** [comment]
The problem with 2 is this redirect: https://github.com/alecthomas/chroma/blob/master/cmd/chroma/go.mod#L5

**Comment by alecthomas** [comment]
Yes, which is resolved by running it from that directory.

**Comment by alecthomas** [comment]
Hmm that optimistic fix did not work, let me take another look.
